# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-ast
      - id: check-docstring-first
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
        args: ["--autofix", "--no-ensure-ascii"]

  # Python hooks
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.289"
    hooks:
      - id: ruff
        args:
          - --fix

  # Notebook hooks
  #- repo: https://github.com/nbQA-dev/nbQA
  #  rev: 1.7.0
  #  hooks:
  #    - id: nbqa-black
  #    - id: nbqa-ruff
  #      args:
  #        - --fix
